# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddEditForm(object):
    def setupUi(self, AddEditForm):
        AddEditForm.setObjectName("AddEditForm")
        AddEditForm.resize(450, 350)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddEditForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineName = QtWidgets.QLineEdit(parent=AddEditForm)
        self.lineName.setObjectName("lineName")
        self.verticalLayout.addWidget(self.lineName)
        self.lineRoast = QtWidgets.QLineEdit(parent=AddEditForm)
        self.lineRoast.setObjectName("lineRoast")
        self.verticalLayout.addWidget(self.lineRoast)
        self.lineGround = QtWidgets.QLineEdit(parent=AddEditForm)
        self.lineGround.setObjectName("lineGround")
        self.verticalLayout.addWidget(self.lineGround)
        self.lineDescription = QtWidgets.QLineEdit(parent=AddEditForm)
        self.lineDescription.setObjectName("lineDescription")
        self.verticalLayout.addWidget(self.lineDescription)
        self.linePrice = QtWidgets.QLineEdit(parent=AddEditForm)
        self.linePrice.setObjectName("linePrice")
        self.verticalLayout.addWidget(self.linePrice)
        self.lineVolume = QtWidgets.QLineEdit(parent=AddEditForm)
        self.lineVolume.setObjectName("lineVolume")
        self.verticalLayout.addWidget(self.lineVolume)
        self.btnSave = QtWidgets.QPushButton(parent=AddEditForm)
        self.btnSave.setObjectName("btnSave")
        self.verticalLayout.addWidget(self.btnSave)

        self.retranslateUi(AddEditForm)
        QtCore.QMetaObject.connectSlotsByName(AddEditForm)

    def retranslateUi(self, AddEditForm):
        _translate = QtCore.QCoreApplication.translate
        AddEditForm.setWindowTitle(_translate("AddEditForm", "Добавить / Изменить кофе"))
        self.lineName.setPlaceholderText(_translate("AddEditForm", "Название"))
        self.lineRoast.setPlaceholderText(_translate("AddEditForm", "Степень обжарки"))
        self.lineGround.setPlaceholderText(_translate("AddEditForm", "Молотый / в зернах"))
        self.lineDescription.setPlaceholderText(_translate("AddEditForm", "Описание вкуса"))
        self.linePrice.setPlaceholderText(_translate("AddEditForm", "Цена"))
        self.lineVolume.setPlaceholderText(_translate("AddEditForm", "Объем (гр)"))
        self.btnSave.setText(_translate("AddEditForm", "Сохранить"))
