# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 550)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableCoffee = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableCoffee.setColumnCount(7)
        self.tableCoffee.setObjectName("tableCoffee")
        self.tableCoffee.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableCoffee.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCoffee.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCoffee.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCoffee.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCoffee.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCoffee.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCoffee.setHorizontalHeaderItem(6, item)
        self.verticalLayout.addWidget(self.tableCoffee)
        self.buttonsLayout = QtWidgets.QHBoxLayout()
        self.buttonsLayout.setObjectName("buttonsLayout")
        self.btnAdd = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAdd.setObjectName("btnAdd")
        self.buttonsLayout.addWidget(self.btnAdd)
        self.btnEdit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnEdit.setObjectName("btnEdit")
        self.buttonsLayout.addWidget(self.btnEdit)
        self.verticalLayout.addLayout(self.buttonsLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Каталог кофе"))
        item = self.tableCoffee.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableCoffee.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Название"))
        item = self.tableCoffee.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Обжарка"))
        item = self.tableCoffee.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Тип"))
        item = self.tableCoffee.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Описание"))
        item = self.tableCoffee.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Цена"))
        item = self.tableCoffee.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Объем"))
        self.btnAdd.setText(_translate("MainWindow", "Добавить"))
        self.btnEdit.setText(_translate("MainWindow", "Изменить"))
